# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LL1(object):
    def setupUi(self, LL1):
        LL1.setObjectName("LL1")
        LL1.resize(1645, 1067)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(LL1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.input = QtWidgets.QFrame(LL1)
        self.input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input.setObjectName("input")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.input)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.openFileFrame = QtWidgets.QFrame(self.input)
        self.openFileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.openFileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.openFileFrame.setObjectName("openFileFrame")
        self.formLayout = QtWidgets.QFormLayout(self.openFileFrame)
        self.formLayout.setObjectName("formLayout")
        self.numOne = QtWidgets.QLabel(self.openFileFrame)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.numOne.setFont(font)
        self.numOne.setObjectName("numOne")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.numOne)
        self.openFileButton = QtWidgets.QPushButton(self.openFileFrame)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.openFileButton.setFont(font)
        self.openFileButton.setObjectName("openFileButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.openFileButton)
        self.verticalLayout_4.addWidget(self.openFileFrame)
        self.inputStr = QtWidgets.QFrame(self.input)
        self.inputStr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputStr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputStr.setObjectName("inputStr")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.inputStr)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.numTwo = QtWidgets.QLabel(self.inputStr)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.numTwo.setFont(font)
        self.numTwo.setObjectName("numTwo")
        self.horizontalLayout_3.addWidget(self.numTwo)
        self.label = QtWidgets.QLabel(self.inputStr)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.inputStr)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.analyzeButton = QtWidgets.QPushButton(self.inputStr)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.analyzeButton.setFont(font)
        self.analyzeButton.setObjectName("analyzeButton")
        self.horizontalLayout_3.addWidget(self.analyzeButton)
        self.verticalLayout_4.addWidget(self.inputStr)
        self.verticalLayout_5.addWidget(self.input)
        self.outputf = QtWidgets.QFrame(LL1)
        self.outputf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputf.setObjectName("outputf")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.outputf)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.WENFA = QtWidgets.QFrame(self.outputf)
        self.WENFA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WENFA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WENFA.setObjectName("WENFA")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.WENFA)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.WENFA)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.GramerList = QtWidgets.QListWidget(self.WENFA)
        self.GramerList.setObjectName("GramerList")
        self.verticalLayout.addWidget(self.GramerList)
        self.horizontalLayout.addWidget(self.WENFA)
        self.FIRST = QtWidgets.QFrame(self.outputf)
        self.FIRST.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FIRST.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FIRST.setObjectName("FIRST")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FIRST)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.FIRST)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.FIRSTlist = QtWidgets.QListWidget(self.FIRST)
        self.FIRSTlist.setObjectName("FIRSTlist")
        self.verticalLayout_2.addWidget(self.FIRSTlist)
        self.horizontalLayout.addWidget(self.FIRST)
        self.FOLLOW = QtWidgets.QFrame(self.outputf)
        self.FOLLOW.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FOLLOW.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FOLLOW.setObjectName("FOLLOW")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.FOLLOW)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.FOLLOW)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.FOLLOWlist = QtWidgets.QListWidget(self.FOLLOW)
        self.FOLLOWlist.setObjectName("FOLLOWlist")
        self.verticalLayout_3.addWidget(self.FOLLOWlist)
        self.horizontalLayout.addWidget(self.FOLLOW)
        self.verticalLayout_5.addWidget(self.outputf)
        self.label_2 = QtWidgets.QLabel(LL1)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.tableWidget = QtWidgets.QTableWidget(LL1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)

        self.retranslateUi(LL1)
        QtCore.QMetaObject.connectSlotsByName(LL1)

    def retranslateUi(self, LL1):
        _translate = QtCore.QCoreApplication.translate
        LL1.setWindowTitle(_translate("LL1", "Form"))
        self.numOne.setText(_translate("LL1", "1."))
        self.openFileButton.setText(_translate("LL1", "从文件导入文法"))
        self.numTwo.setText(_translate("LL1", "2."))
        self.label.setText(_translate("LL1", "输入待分析串："))
        self.analyzeButton.setText(_translate("LL1", "分析"))
        self.label_4.setText(_translate("LL1", "文法:"))
        self.label_5.setText(_translate("LL1", "所有文法符号及候选项的FIRST集"))
        self.label_6.setText(_translate("LL1", "非终结符的FOLLOW集："))
        self.label_2.setText(_translate("LL1", "预测分析表"))
